# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12t0Lkim41bDjoCi91EOAZdRuxdfZI1P5
"""

IDE:
uzywane: IDLE, Spyder, Notepad++, PyCharm, Jupyter

math % give rest f.ex. 6.4%2 = 0.4

6.4%2

f *= i
f *=i == f=f*i

i = 1
f = 1
while (i<100):
  f*=i
  i*=1
print(f)

ord("a")
ord("B")

bool(-3)
bool(2)

def facultative(x):
  fac = 1
  while x>1:
    fac = fac * x
    x=x-1
  return fac
print(facultative(10))

d = {"John"}

n=0
for i in range(17, 1000000, 17):
  if str(i) == str(i)[::-1]:
    n += 1
  print(i)
print(n)