# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XFBDiWz8XgKfVKQAjdV-EaAa6z_40gGJ
"""

list_1 = [1,2,3]
for monkey in list_1:
  print(monkey)

list_1 = ["Ben", "Nan", "Daniel"]
for name in list_1:
  print("Hello", name, "thanks for being here. Your name have" len(name), "letters")

list_1 = ["Ben", "Nan", "Daniel"]
empty_list = []

for name in list_1:
  sentence = "Hello", + element + , "thanks for being here. Your name have" len(name), "letters"
  #element.added.v...5t3423t5y6y4tgfrde34ty6hre
  print("Hello", name, "thanks for being here. Your name have" len(name), "letters")

total_sum = 0
for element in range(100):
  total_sum = total_sum + element
total_sum

total_sum = 0
for element in range(6):
  total_sum = total_sum + element
  print(total_sum)
print(total_sum)

#place important

while something_is_true:
  print('hi')

  #no run

if something:
  do this
else:
  do that

name = "Benjamin"
if name == "Benjamin":
  print("Hi Ben!")
else:
  print("You are no Ben, go away!")

temperature = 15
if temperature > 20:
  print("It is hot outside")
elif temperature >=15:
    print("Danish summer")
else:
  print("Welcome to Denmark!")

temperature = 25
if 10 > temperature > 20:
  print("It is hot outside")
elif temperature >=15:
    print("Danish summer")
else:
  print("Welcome to Denmark!")

list_of_tmp = [0,2,4,6,8,10,12]
for element in list_of_tmp:
  if element > 8:
    print('wear shorts')
  elif element > 4:
    print('wear long pants')
  else:
    print('wear whatever')

list_of_tmp = [0,2,4,6,8,10,12]
temperature = 0
while temperature < 8:
  print('The temperature we check now is:', temperature, ' we + 2')
  print('stay home')
  temperature = temperature + 2
  print('The new temperature now is:', temperature)
  print()

powerShell: yupiter lab or J