# -*- coding: utf-8 -*-
"""Kopia notatnika Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XIY8RtxUk3KNT0VyhepkKWVTkNmDN3nn
"""

type(48)

type("hello KUB Datalab")

type(29.6)

type(True)

"THIS IS string"

"this is 'also' a string"

#comment

"I am a string [7]"[7]

"I am a string" [0:7]

"I am a string " + "and so am I"

4*2

4**2

72%10

40/7

13 < 17

13>17

print(5-3)

print("hello" - "h")

"string" + "string"

'some text' *10

print(1+'2')

print(1 + int('2'))

print("half is", 1/2.0)

first = 1
second = 5* first
first = 2
print("first is", first, "")

First_Name = mihu

first_name = "Nynne"
age=18
print(first_name, "is", age)

age = age + 4
print("age in 4 years", age)

print('hello class') #this is comment

print('hello class','elo elo')

print('something')
print()
print('trala')

#max and min
#0-9, a-z, A-Z
print(max(1,2,3))
print(max('a','b','e','r','g'))

help(max)

a=34.5
round(a)

andres = 636363.83838338
round(andres, 2)

help(round)

result = print('example')
print('tralalalbum is' + result)

#lists
my_first_list = []
temps = [16.5, 13.4, 17, 'feelin hot hot']
print(temps)

temps[0:3]

temps[3] = 15.6
print(temps)

temps.append(17.9)
print(temps)

del temps[2]
print(temps)

#ex
values = []
values.append(1)
values.append(3)
values.append(5)
print('first time:', values)
values = values[1:3]
print('second time:', values)

len(values) #lenght

print('string to list:', list('tin'))
print('list to string:', ''.join(['g', 'o', 'l', 'd']))
print('list to string:', '-'.join(['g', 'o', 'l', 'd']))

element = 'helium'
print(element[-1])
print(element[0:-1])

# Program A
letters = list('gold')
result = sorted(letters)
print('letters is', letters, 'and result is', result)
# Program B
letters = list('gold')
result = letters.sort()
print('letters is', letters, 'and result is', result)

